# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shopsN2.0' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'EaseMobSDKFull'
   pod 'IQKeyboardManager'
   pod 'AFNetworking'
   pod 'JPush'
   
  # Pods for shopsN2.0

  target 'shopsN2.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shopsN2.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
